name: Actionlint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            action:
              - '.github/workflows/**'
        
      - name: Download Actionlint
        id: actionlint
        if: ${{ steps.filter.outputs.action == 'true' }}
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Check workflow files
        if: ${{ steps.filter.outputs.action == 'true' }}
        run: ${{ steps.actionlint.outputs.executable }} -color
        shell: bash
