name: Dependabot auto-merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == dependabot[bot]

    steps:
      - name: Fetch Metadata from Dependabot PRs
        uses: dependabot/fetch-metadata@v1
        id: metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-merge
        if: steps.metadata.outputs.update-type == version-update:semver-patch
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
