name: Google Java Format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Paths Changes Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            java:
              - '**/*.java'
   
      - name: Setup Java JDK
        if: |
          steps.filter.outputs.java == 'true' ||
          github.event_name == 'workflow_dispatch'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: maven
  
      - name: Google Java Format
        if: |
          steps.filter.outputs.java == 'true' ||
          github.event_name == 'workflow_dispatch'
        uses: axel-op/googlejavaformat-action@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
