name: Vanilla Packs Download

on:
  schedule:
    - cron: '00 22 * * 4'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      BEHAVIOR_URL: https://aka.ms/behaviorpacktemplate
      BEHAVIOR_DIR: src/main/resources/vanilla_packs/behavior
      BEHAVIOR_TEMP: ./tmp/behavior.zip
      RESOURCE_URL: https://aka.ms/resourcepacktemplate
      RESOURCE_DIR: src/main/resources/vanilla_packs/resource
      RESOURCE_TEMP: ./tmp/resource.zip
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: |
          filename=$(curl -I $BEHAVIOR_URL)
          echo "::set-output name=version::${filename#Vanilla-Behavior_Pack_%.zip}"
        id: version

      - name: Create Directories
        run: |
          mkdir -p ./tmp
          mkdir -p $BEHAVIOR_DIR
          mkdir -p $RESOURCE_DIR

      - name: Clean Directories
        run: |
          rm -rf $BEHAVIOR_DIR
          rm -rf $RESOURCE_DIR

      - name: Download
        run: |
          curl -L $BEHAVIOR_URL -o $BEHAVIOR_TEMP
          curl -L $RESOURCE_URL -o $RESOURCE_TEMP

      - name: Unzip
        run: |
          unzip $BEHAVIOR_TEMP -d $BEHAVIOR_DIR
          unzip $RESOURCE_TEMP -d $RESOURCE_DIR

      - name: Setup Git Configs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push
        run: |
          git add .
          git commit -m "Vanilla Packs Update ${{ steps.version.outputs.version }}"
          git push origin main
