name: Vanilla Packs Download

on:
  schedule:
    - cron: '00 22 * * 4'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      BEHAVIOR: src/main/resources/vanilla_packs/behavior
      BEHAVIOR_TEMP: ./tmp/behavior.zip
      RESOURCE: src/main/resources/vanilla_packs/resource
      RESOURCE_TEMP: ./tmp/resource.zip
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Directories
        run: |
          mkdir -p ./tmp
          mkdir -p $BEHAVIOR
          mkdir -p $RESOURCE

      - name: Clean Directories
        run: |
          rm -rf $BEHAVIOR
          rm -rf $RESOURCE

      - name: Download
        run: |
          curl -L https://aka.ms/behaviorpacktemplate -o $BEHAVIOR_TEMP
          curl -L https://aka.ms/resourcepacktemplate -o $RESOURCE_TEMP

      - name: Unzip
        run: |
          unzip $BEHAVIOR_TEMP -d $BEHAVIOR
          unzip $RESOURCE_TEMP -d $RESOURCE

      - name: Setup Git Configs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Push
        run: |
          git add .
          git commit -m 1.19.10
          git push origin main
